// Generated by CoffeeScript 1.4.0
(function() {
  var status;

  window.App = {};

  App.status = status = function(s) {
    if (typeof console !== "undefined" && console !== null) {
      console.log(s);
    }
    return $('#status').html(s);
  };

  App.status("main.coffee has begun!");

  App.tiles = {};

  App.objects = {};

  App.players = {};

  App.collision = {};

  App.actionHandlers = {};

}).call(this);
