// Generated by CoffeeScript 1.4.0
(function() {
  var start, status;

  window.App = {};

  $('#log').html('');

  start = new Date().getTime();

  App.status = status = function(s) {
    var t;
    if (typeof console !== "undefined" && console !== null) {
      console.log(s);
    }
    t = (new Date().getTime() - start) / 1000;
    return $('#log').html("<tr><td>" + t + "</td><td>" + s + "</td></tr>" + ($('#log').html()));
  };

  App.status("main.coffee has begun!");

  App.tiles = {};

  App.objects = {};

  App.players = {};

  App.collision = {};

  App.actionHandlers = {};

}).call(this);
