// Generated by CoffeeScript 1.4.0
(function() {
  var exampleBoxHandler, simpleDumbHandler;

  simpleDumbHandler = {
    leftClick: function(cobject, sendAction) {
      return sendAction({
        action: 'ACTIVATE'
      });
    },
    rightClick: function(cobject, sendAction) {
      return alert(JSON.stringify(cobject));
    }
  };

  exampleBoxHandler = {
    leftClick: function(cobject, sendAction) {
      if (cobject.clickedFiveTimes) {
        alert('Woah, you\'re clicking a lot!  Take it easy.  RSI can be a bitch.');
      }
      return sendAction({
        action: 'ACTIVATE'
      });
    }
  };

  App.actionHandlers = {};

  App.actionHandlers['CDoor'] = simpleDumbHandler;

  App.actionHandlers['CDoorSwitch'] = simpleDumbHandler;

  App.actionHandlers['CExampleBox'] = exampleBoxHandler;

}).call(this);
