// Generated by CoffeeScript 1.4.0
(function() {
  var simpleDumbHandler;

  simpleDumbHandler = {
    leftClick: function(cobject, sendAction) {
      return sendAction({
        action: 'ACTIVATE'
      });
    },
    rightClick: function(cobject, sendAction) {
      return alert(JSON.stringify(cobject));
    }
  };

  App.actionHandlers = {};

  App.actionHandlers['CDoor'] = simpleDumbHandler;

  App.actionHandlers['CDoorSwitch'] = simpleDumbHandler;

}).call(this);
