// Generated by CoffeeScript 1.4.0
(function() {
  var cx, cy;

  cx = $('#canvas')[0].offsetLeft;

  cy = $('#canvas')[0].offsetTop;

  $('body').on('contextmenu', function() {
    return false;
  });

  $('#canvas').mousedown(function(mev) {
    var a, ah, b, chandle, depth, layer, mx, my, o, x, y, _ref, _ref1, _ref2, _results;
    if ((mev.offsetX != null) && (mev.offsetY != null)) {
      mx = mev.offsetX;
      my = mev.offsetY;
    } else {
      mx = mev.pageX - cx;
      my = mev.pageY - cy;
    }
    _ref = App.graphics.mouseToTileCoords(mx, my), x = _ref[0], y = _ref[1];
    _ref1 = App.tiles;
    _results = [];
    for (depth in _ref1) {
      layer = _ref1[depth];
      if ((layer != null) && (layer[y] != null) && (layer[y][x] != null)) {
        _ref2 = layer[y][x], a = _ref2[0], b = _ref2[1], chandle = _ref2[2];
        console.log("-chandle " + chandle);
        if (App.objects[chandle] != null) {
          o = App.objects[chandle];
          console.log("-- got o");
          if ((o.type != null) && (App.actionHandlers[o.type] != null)) {
            App.ah = ah = App.actionHandlers[o.type];
            console.log("--- ahhhh for type " + o.type + "  +  " + (JSON.stringify(ah)));
            if (mev.which === 1) {
              if (ah.leftClick != null) {
                _results.push(ah.leftClick(o, function(p) {
                  return App.netsend({
                    id: 'ACTION',
                    chandle: chandle,
                    p: p
                  });
                }));
              } else {
                _results.push(void 0);
              }
            } else {
              if (ah.rightClick != null) {
                _results.push(ah.rightClick(o, function(p) {
                  return App.netsend({
                    id: 'ACTION',
                    chandle: chandle,
                    p: p
                  });
                }));
              } else {
                _results.push(void 0);
              }
            }
          } else {
            _results.push(void 0);
          }
        } else {
          _results.push(App.status(' clicked tile contained object, but the object hasn\'t been synced to the client!!'));
        }
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
